---
version: '3'

services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  wordpress:
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - db
    image: wordpress:6.6.2-php8.1-apache
    ports:
      - 8072:80
    restart: always
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/benignware-connect
    working_dir: /var/www/html
  wp:
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    image: wordpress:cli
    user: '33:33'
    depends_on:
      - db
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/benignware-connect
    links:
      - db:db
    command: "--info"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8073:80
    volumes:
      - /sessions
  composer:
    image: composer
    command: install
    working_dir: /var/www/html
    depends_on:
      - wordpress
    volumes:
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/benignware-connect
    links:
      - wordpress:wordpress
volumes:
  db_data:
  wordpress: